[package]
name = "bevy_asset_preload"
version = "1.2.0"
edition = "2024"

[dependencies]
bevy_app = "0.18"
bevy_asset = "0.18"
bevy_ecs = "0.18"
bevy_state = "0.18"
load_assets = {path = "load_assets" }

[workspace]
members = [
    "load_assets"
]
